-- Sistema de soporte: tickets entre un usuario (atleta o entrenador) y el equipo de Training ProgLine.
--
-- Nada que ver con `trainer_messages`, que es la conversación entrenador ↔ atleta.
-- Aquí la relación es USUARIO ↔ EQUIPO, y solo el administrador gestiona la bandeja.
--
-- Estados:    open | in_progress | waiting_user | resolved | closed
-- Prioridad:  low | normal | high | urgent
-- Categorías: technical | account | programs | workouts | billing | suggestion | other

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  -- Identificador legible para comunicar al usuario (TP-000123). Lo genera Postgres, nunca el cliente.
  ticket_number bigint generated by default as identity unique,
  requester_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null default '',
  requester_email text not null default '',
  requester_role text not null default 'atleta' check (
    requester_role in ('atleta', 'entrenador', 'administrador')
  ),
  category text not null default 'other' check (
    category in ('technical', 'account', 'programs', 'workouts', 'billing', 'suggestion', 'other')
  ),
  subject text not null check (char_length(trim(subject)) between 1 and 150),
  status text not null default 'open' check (
    status in ('open', 'in_progress', 'waiting_user', 'resolved', 'closed')
  ),
  priority text not null default 'normal' check (
    priority in ('low', 'normal', 'high', 'urgent')
  ),
  assigned_admin_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz
);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_role text not null check (
    sender_role in ('atleta', 'entrenador', 'administrador')
  ),
  message text not null check (char_length(trim(message)) between 1 and 5000),
  -- Nota interna del equipo: nunca la ve el usuario (ver políticas de select).
  is_internal boolean not null default false,
  created_at timestamptz not null default now(),
  read_by_admin_at timestamptz,
  read_by_user_at timestamptz
);

-- ---- Índices ----

create index if not exists support_tickets_requester_idx
  on public.support_tickets (requester_id, created_at desc);
create index if not exists support_tickets_status_idx
  on public.support_tickets (status);
create index if not exists support_tickets_assigned_idx
  on public.support_tickets (assigned_admin_id);
create index if not exists support_tickets_last_message_idx
  on public.support_tickets (last_message_at desc);
create index if not exists support_messages_ticket_idx
  on public.support_messages (ticket_id, created_at);

-- ---- updated_at / resolved_at / closed_at gestionados por Postgres ----

create or replace function public.support_tickets_before_update()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();

  if new.status = 'resolved' and old.status is distinct from 'resolved' then
    new.resolved_at := now();
  elsif new.status <> 'resolved' then
    new.resolved_at := null;
  end if;

  if new.status = 'closed' and old.status is distinct from 'closed' then
    new.closed_at := now();
  elsif new.status <> 'closed' then
    new.closed_at := null;
  end if;

  return new;
end;
$$;

drop trigger if exists support_tickets_before_update_trg on public.support_tickets;
create trigger support_tickets_before_update_trg
  before update on public.support_tickets
  for each row execute function public.support_tickets_before_update();

-- Cada mensaje mueve `last_message_at` y aplica la transición de estado.
-- Centralizado aquí para que ninguna pantalla pueda dejar el estado incoherente.
create or replace function public.support_messages_after_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_internal then
    update public.support_tickets
    set updated_at = now()
    where id = new.ticket_id;
    return new;
  end if;

  update public.support_tickets t
  set
    last_message_at = new.created_at,
    status = case
      when t.status = 'closed' then t.status
      when new.sender_id is not distinct from t.requester_id then
        -- Responde el usuario: si esperábamos su respuesta, vuelve a estar en curso.
        case when t.status in ('waiting_user', 'resolved') then 'in_progress' else t.status end
      else
        -- Responde el equipo: queda pendiente de que conteste el usuario.
        case when t.status in ('open', 'in_progress') then 'waiting_user' else t.status end
    end
  where t.id = new.ticket_id;

  return new;
end;
$$;

drop trigger if exists support_messages_after_insert_trg on public.support_messages;
create trigger support_messages_after_insert_trg
  after insert on public.support_messages
  for each row execute function public.support_messages_after_insert();

-- ---- RLS ----

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;

-- Tickets: el usuario solo los suyos.
drop policy if exists "Users view own support tickets" on public.support_tickets;
create policy "Users view own support tickets"
  on public.support_tickets for select
  to authenticated
  using (requester_id = auth.uid());

drop policy if exists "Admins view all support tickets" on public.support_tickets;
create policy "Admins view all support tickets"
  on public.support_tickets for select
  to authenticated
  using (public.is_administrador());

-- El alta normal va por create_support_ticket(). Si se inserta directo, solo para uno mismo
-- y sin poder fijar prioridad, estado ni administrador asignado.
drop policy if exists "Users create own support tickets" on public.support_tickets;
create policy "Users create own support tickets"
  on public.support_tickets for insert
  to authenticated
  with check (
    requester_id = auth.uid()
    and status = 'open'
    and priority = 'normal'
    and assigned_admin_id is null
  );

-- Solo el administrador cambia estado, prioridad o asignación. El usuario no tiene UPDATE.
drop policy if exists "Admins manage support tickets" on public.support_tickets;
create policy "Admins manage support tickets"
  on public.support_tickets for all
  to authenticated
  using (public.is_administrador())
  with check (public.is_administrador());

-- Mensajes: el usuario ve los de sus tickets y nunca las notas internas.
drop policy if exists "Users view own ticket messages" on public.support_messages;
create policy "Users view own ticket messages"
  on public.support_messages for select
  to authenticated
  using (
    is_internal = false
    and exists (
      select 1
      from public.support_tickets t
      where t.id = support_messages.ticket_id
        and t.requester_id = auth.uid()
    )
  );

drop policy if exists "Admins view all support messages" on public.support_messages;
create policy "Admins view all support messages"
  on public.support_messages for select
  to authenticated
  using (public.is_administrador());

-- El usuario responde solo en sus tickets no cerrados, nunca como interno
-- y sin poder falsear su rol.
drop policy if exists "Users reply to own support tickets" on public.support_messages;
create policy "Users reply to own support tickets"
  on public.support_messages for insert
  to authenticated
  with check (
    sender_id = auth.uid()
    and is_internal = false
    and sender_role = coalesce(public.current_user_role_slug(), 'atleta')
    and exists (
      select 1
      from public.support_tickets t
      where t.id = support_messages.ticket_id
        and t.requester_id = auth.uid()
        and t.status <> 'closed'
    )
  );

drop policy if exists "Admins manage support messages" on public.support_messages;
create policy "Admins manage support messages"
  on public.support_messages for all
  to authenticated
  using (public.is_administrador())
  with check (public.is_administrador());

-- ---- Alta atómica del ticket + primer mensaje ----

create or replace function public.create_support_ticket(
  p_category text,
  p_subject text,
  p_message text
)
returns public.support_tickets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text;
  v_email text;
  v_role text;
  v_category text;
  v_ticket public.support_tickets;
begin
  if v_user_id is null then
    raise exception 'Necesitas iniciar sesión para enviar una solicitud';
  end if;

  if p_subject is null or char_length(trim(p_subject)) = 0 then
    raise exception 'El asunto es obligatorio';
  end if;

  if p_message is null or char_length(trim(p_message)) = 0 then
    raise exception 'El mensaje es obligatorio';
  end if;

  -- Los datos del solicitante salen de la sesión, nunca del cliente.
  select
    coalesce(nullif(trim(p.name), ''), 'Usuario'),
    coalesce(p.email, ''),
    coalesce(r.slug, 'atleta')
  into v_name, v_email, v_role
  from public."Perfil" p
  left join public.roles r on r.id = p.id_roles
  where p.id = v_user_id;

  if v_name is null then
    v_name := 'Usuario';
    v_email := coalesce((select u.email from auth.users u where u.id = v_user_id), '');
    v_role := 'atleta';
  end if;

  v_category := coalesce(nullif(trim(p_category), ''), 'other');
  if v_category not in ('technical', 'account', 'programs', 'workouts', 'billing', 'suggestion', 'other') then
    v_category := 'other';
  end if;

  insert into public.support_tickets (
    requester_id, requester_name, requester_email, requester_role, category, subject
  )
  values (
    v_user_id, v_name, v_email, v_role, v_category, left(trim(p_subject), 150)
  )
  returning * into v_ticket;

  insert into public.support_messages (ticket_id, sender_id, sender_role, message)
  values (v_ticket.id, v_user_id, v_role, trim(p_message));

  return v_ticket;
end;
$$;

grant execute on function public.create_support_ticket(text, text, text) to authenticated;

-- ---- Marcar como leído ----
-- Por RPC para no dar UPDATE sobre support_messages a los usuarios normales.

create or replace function public.mark_support_messages_read(p_ticket_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_requester uuid;
begin
  if v_user_id is null then
    return;
  end if;

  select requester_id into v_requester
  from public.support_tickets
  where id = p_ticket_id;

  if v_requester is null then
    return;
  end if;

  if public.is_administrador() then
    update public.support_messages
    set read_by_admin_at = now()
    where ticket_id = p_ticket_id
      and read_by_admin_at is null
      and sender_id is not distinct from v_requester;
    return;
  end if;

  if v_requester = v_user_id then
    update public.support_messages
    set read_by_user_at = now()
    where ticket_id = p_ticket_id
      and read_by_user_at is null
      and is_internal = false
      and sender_id is distinct from v_requester;
  end if;
end;
$$;

grant execute on function public.mark_support_messages_read(uuid) to authenticated;

-- ---- Contadores de no leídos ----
-- security_invoker: la vista respeta la RLS del que consulta, así que un usuario
-- solo obtiene filas de sus propios tickets.

drop view if exists public.support_ticket_unread;
create view public.support_ticket_unread
with (security_invoker = true)
as
select
  t.id as ticket_id,
  count(m.id) filter (
    where m.sender_id is not distinct from t.requester_id
      and m.read_by_admin_at is null
      and m.is_internal = false
  ) as unread_for_admin,
  count(m.id) filter (
    where m.sender_id is distinct from t.requester_id
      and m.read_by_user_at is null
      and m.is_internal = false
  ) as unread_for_user
from public.support_tickets t
left join public.support_messages m on m.ticket_id = t.id
group by t.id;

grant select on public.support_ticket_unread to authenticated;
