import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sql = readFileSync(join(__dirname, '..', 'supabase', 'support-tickets.sql'), 'utf8');

/** SQL sin comentarios, para comprobar lo que realmente se ejecuta. */
const statements = sql
  .split('\n')
  .filter((line) => !line.trimStart().startsWith('--'))
  .join('\n');

/** Devuelve el cuerpo de una política por nombre, para poder inspeccionar su `using`/`with check`. */
function policyBody(name) {
  const start = sql.indexOf(`create policy "${name}"`);
  assert.notEqual(start, -1, `Falta la política "${name}"`);

  const end = sql.indexOf('\n\n', start);
  return sql.slice(start, end === -1 ? sql.length : end);
}

describe('esquema de soporte', () => {
  it('separa soporte de la conversación entrenador-atleta', () => {
    assert.match(sql, /create table if not exists public\.support_tickets/);
    assert.match(sql, /create table if not exists public\.support_messages/);
    assert.doesNotMatch(statements, /trainer_messages/);
  });

  it('genera el número de ticket en la base de datos, no en el cliente', () => {
    assert.match(sql, /ticket_number bigint generated by default as identity unique/);
  });

  it('activa RLS en las dos tablas', () => {
    assert.match(sql, /alter table public\.support_tickets enable row level security/);
    assert.match(sql, /alter table public\.support_messages enable row level security/);
  });

  it('indexa las columnas que se consultan', () => {
    for (const column of ['requester_id', 'status', 'assigned_admin_id', 'last_message_at']) {
      assert.ok(
        sql.includes(`support_tickets (${column}`) || sql.includes(`support_tickets (${column},`),
        `Falta índice para ${column}`,
      );
    }
    assert.match(sql, /support_messages_ticket_idx/);
  });
});

describe('permisos del usuario', () => {
  it('solo puede ver sus propios tickets', () => {
    assert.match(policyBody('Users view own support tickets'), /requester_id = auth\.uid\(\)/);
  });

  it('no puede fijar prioridad, estado ni administrador al crear', () => {
    const body = policyBody('Users create own support tickets');
    assert.match(body, /requester_id = auth\.uid\(\)/);
    assert.match(body, /status = 'open'/);
    assert.match(body, /priority = 'normal'/);
    assert.match(body, /assigned_admin_id is null/);
  });

  it('no tiene ninguna política de update sobre los tickets', () => {
    const updatePolicies = sql
      .split('create policy')
      .filter((chunk) => /on public\.support_tickets for (update|all)/.test(chunk));

    assert.ok(updatePolicies.length > 0, 'Debe existir al menos la política de administrador');
    for (const chunk of updatePolicies) {
      assert.match(
        chunk,
        /public\.is_administrador\(\)/,
        'Cambiar un ticket debe exigir is_administrador()',
      );
    }
  });

  it('nunca ve las notas internas', () => {
    const body = policyBody('Users view own ticket messages');
    assert.match(body, /is_internal = false/);
    assert.match(body, /t\.requester_id = auth\.uid\(\)/);
  });

  it('solo responde en sus tickets no cerrados y sin falsear su rol', () => {
    const body = policyBody('Users reply to own support tickets');
    assert.match(body, /sender_id = auth\.uid\(\)/);
    assert.match(body, /is_internal = false/);
    assert.match(body, /sender_role = coalesce\(public\.current_user_role_slug\(\)/);
    assert.match(body, /t\.status <> 'closed'/);
  });
});

describe('permisos del administrador', () => {
  it('usa is_administrador() y no el rol que diga el cliente', () => {
    assert.match(policyBody('Admins view all support tickets'), /public\.is_administrador\(\)/);
    assert.match(policyBody('Admins manage support tickets'), /public\.is_administrador\(\)/);
    assert.match(policyBody('Admins view all support messages'), /public\.is_administrador\(\)/);
    assert.match(policyBody('Admins manage support messages'), /public\.is_administrador\(\)/);
  });
});

describe('funciones', () => {
  it('crea ticket y primer mensaje de forma atómica', () => {
    const start = sql.indexOf('create or replace function public.create_support_ticket');
    assert.notEqual(start, -1);

    const body = sql.slice(start, sql.indexOf('grant execute on function public.create_support_ticket'));
    assert.match(body, /security definer/);
    assert.match(body, /insert into public\.support_tickets/);
    assert.match(body, /insert into public\.support_messages/);
  });

  it('toma la identidad del solicitante de la sesión, no de los parámetros', () => {
    const start = sql.indexOf('create or replace function public.create_support_ticket');
    const body = sql.slice(start, sql.indexOf('grant execute on function public.create_support_ticket'));

    assert.match(body, /v_user_id uuid := auth\.uid\(\)/);
    assert.doesNotMatch(body, /p_requester_id/);
    assert.doesNotMatch(body, /p_role/);
  });

  it('la vista de no leídos respeta la RLS de quien consulta', () => {
    assert.match(sql, /create view public\.support_ticket_unread\s*\nwith \(security_invoker = true\)/);
  });

  it('centraliza la transición de estado en un trigger', () => {
    const start = sql.indexOf('create or replace function public.support_messages_after_insert');
    assert.notEqual(start, -1);

    const body = sql.slice(start, sql.indexOf('drop trigger if exists support_messages_after_insert_trg'));
    // El usuario reabre, el equipo deja el ticket esperando respuesta, y lo cerrado no se mueve.
    assert.match(body, /when t\.status = 'closed' then t\.status/);
    assert.match(body, /'in_progress'/);
    assert.match(body, /'waiting_user'/);
  });
});
